### ISSUE TITLE
Optimal Instruction Decoder

### ISSUE THREAD

**Issue by adamsmd** [timlg07/TheNandGame-solutions#4]
Instruction Decoder can be done in only 4 components:

![Screenshot from 2020-12-23 12-22-10](https://user-images.githubusercontent.com/310140/103022364-d382dd80-4519-11eb-95c7-1b5cf3bc30bb.png)

**Comment by timlg07** [comment]
Thanks for providing this solution! The previous one was a total mess, I don't know what I was thinking when I did this :D
